[package]
name = "lockyleaks"
version = "0.1.0"
authors = ["Oliver Gould <ver@buoyant.io>"]
edition = "2018"

[dependencies]
futures = "0.3"
tokio = { version = "0.2", features = ["full"] }
pin-project = "0.4.8"
